### ISSUE TITLE
Missing properties from Conn (Deno 1.19)

### ISSUE THREAD

**Issue by NextFire** [DjDeveloperr/deno_namedpipe#3]
The Conn interface has been updated on Deno 1.19 (https://deno.com/blog/v1.19#files-network-sockets-and-stdio-are-now-native-web-streams). Can you update the library according to this change?

I am using [discord_rpc](https://github.com/harmonyland/discord_rpc) which relies on this library and it seems to be crashing now (https://github.com/NextFire/apple-music-discord-rpc/issues/9)

**Comment by DjDeveloperr** [comment]
Streams would be actually worth implementing since they have nicer interface. I'll try to implement it ASAP

**Comment by DjDeveloperr** [comment]
Also, until the streams are implemented here, you can run with `--no-check=remote`
